name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Run TypeScript
        run: yarn tsc:full

      - name: Lint the code
        run: yarn lint:all

      - name: Run tests
        run: yarn test

      - name: Build the plugin
        run: yarn build
