name: Build

on:
  pull_request:
  push:
    branches:
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Run TypeScript checks
        run: yarn tsc:full

      # These validations could be skipped on main as they're style/convention checks
      - name: Lint the code
        if: github.event_name == 'pull_request'
        run: yarn lint:all

      - name: Run tests
        if: github.event_name == 'pull_request'
        run: yarn test

      - name: Build the plugin
        run: yarn build
